DROOLS-7475 Proposed feature for ['key'] accessor (#56)
* DROOLS-7475 Proposed feature for ['key'] accessor

nesting the protoextractor into the maven build

* WIP: broken but progressing

Results :

Failed tests:   testWithSelectAttr(org.drools.ansible.rulebook.integration.api.NullTest): expected:<1> but was:<0>
  test(org.drools.ansible.rulebook.integration.api.NullTest): expected:<1> but was:<0>
  testRepeatedOnceWithin(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinWithOr(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinWithAnd(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testSelectOnNull(org.drools.ansible.rulebook.integration.api.SelectTest): expected:<1> but was:<0>

Tests in error:
  testOnceWithinInRule(org.drools.ansible.rulebook.integration.api.OnceWithinTest): Cannot invoke "java.util.Map.get(Object)" because "map" is null
  testOnceWithinInCondition(org.drools.ansible.rulebook.integration.api.OnceWithinTest): Cannot invoke "java.util.Map.get(Object)" because "map" is null
  testOnceAfterWithOr(org.drools.ansible.rulebook.integration.api.OnceAfterTest): Cannot invoke "Object.toString()" because the return value of "org.drools.base.facttemplates.Fact.get(String)" is null

Tests run: 138, Failures: 6, Errors: 3, Skipped: 0

* WIP: broken but null != UNDEF

Results :

Failed tests:   testRepeatedOnceWithin(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinWithOr(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinWithAnd(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>

Tests in error:
  testOnceWithinInRule(org.drools.ansible.rulebook.integration.api.OnceWithinTest): Cannot invoke "java.util.Map.get(Object)" because "map" is null
  testOnceWithinInCondition(org.drools.ansible.rulebook.integration.api.OnceWithinTest): Cannot invoke "java.util.Map.get(Object)" because "map" is null
  testOnceAfterWithOr(org.drools.ansible.rulebook.integration.api.OnceAfterTest): Cannot invoke "Object.toString()" because the return value of "org.drools.base.facttemplates.Fact.get(String)" is null

Tests run: 138, Failures: 3, Errors: 3, Skipped: 0

* WIP: broken but progressing

Failed tests:   testRepeatedOnceWithin(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinInRule(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinWithOr(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinWithAnd(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceWithinInCondition(org.drools.ansible.rulebook.integration.api.OnceWithinTest): expected:<0> but was:<1>
  testOnceAfterWithOr(org.drools.ansible.rulebook.integration.api.OnceAfterTest): expected:<2> but was:<1>

Tests run: 138, Failures: 6, Errors: 0, Skipped: 0

* ALL tests passing

* small refactor

* cleanup RulesModelUtil

* refactor, small fix for array access, tests

* fix grammar typo

* refactor ExistsField as discussed with Mario

* implement code review feedback

* implement code review feedback

* code review feedback impl about ORIGINAL_MAP_FIELD

* BREAKING to investigate indexing issue

* revert the disabled commit

* implement code review feedback

* code review feedback